# This is a workflow to build and push the Docker app once a new release is published.

name: Docker deploy to release

# Controls when the workflow will run
on:
  # Triggers the workflow when a release is published
  release:
    types: [published]
    branches-ignore:
      - main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.merged == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Installs Task binary
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: # optional
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Docker Metadata action
        id: metadata
        uses: docker/metadata-action@v3.6.0
        with:
          # List of Docker images to use as base name for tags
          images: haroondogar/devopstask 

      # Builds the docker app and pushes to registry
      - name: Build and push the Docker app
        run: |
          cd app
          task docker:build-to-release -- ${{ steps.metadata.outputs.tags }}
