# This is a Unit Test workflow for Pull Requests.

name: Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow when a pull request is created but only for the master branch
  pull_request:
    branches: [ main ]
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
        run: |
          pwd
          ls

      # Installs Task binary
      - name: Install Task
        uses: arduino/setup-task@v1

      # Runs a docker app on port 8080
      - name: Run Docker image
      - run: task docker:run
        
      # Runs the npm tests
      - name: Run npm tests
        run: npm test
